all:
	gcc -std=gnu99 -o contains contains.c
	gcc -std=gnu99 -o fib fibonacci.c
	gcc -std=gnu99 -o isbalanced isbalanced.c
	gcc -std=gnu99 -o ispalendrome	ispalendrome.c
	gcc -std=gnu99 -o rpn rpn.c
	gcc -std=gnu99 -o sllist sllist.c
	gcc -std=gnu99 -o sortmatrix sortmatrix.c
	gcc -std=gnu99 -o tohexbin tohexbin.c
	gcc -std=gnu99 -o wordcounter wordcounter.c
	gcc -std=gnu99 -o wordcounterimproved wordcounterimproved.c
